"""empty message

Revision ID: 97763996fd79
Revises: 2932b012adcd
Create Date: 2021-04-07 00:41:00.994070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97763996fd79'
down_revision = '2932b012adcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.drop_column('Artist', 'website')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'website_link')
    # ### end Alembic commands ###
